const BROKER_MESSAGES_TYPES = {
  PROXY_CLIENT_EVENT: 'proxy_client_event',
  PROXY_SERVER_EVENT: 'proxy_server_event',
};

const ERROR_TYPES = {
  INTERNAL_FAILURE: 'ERR_INTERNAL_FAILURE',
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  UNAUTHORISED: 'ERR_UNAUTHORISED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  CONFLICT: 'ERR_CONFLICT',
  CLIENT_TYPE_NOT_SUPPORTED: 'ERR_CLIENT_TYPE_NOT_SUPPORTED',
  EVENT_HANDLER_NOT_FOUND: 'ERR_EVENT_HANDLER_NOT_FOUND',
  REQUEST_TIMED_OUT: 'ERR_REQUEST_TIMED_OUT',
  PROCESSING_FAILED: 'ERR_PROCESSING_FAILED',
  PASSWORD_REQUIRED: 'ERR_PASSWORD_REQUIRED',
};

module.exports = {
  BROKER_MESSAGES_TYPES,
  ERROR_TYPES,
};
