const INTERNAL_FAILURE = 'ERR_INTERNAL_FAILURE';
const BAD_REQUEST = 'ERR_BAD_REQUEST';
const UNAUTHORISED = 'ERR_UNAUTHORISED';
const FORBIDDEN = 'ERR_FORBIDDEN';
const NOT_FOUND = 'ERR_NOT_FOUND';
const CONFLICT = 'ERR_CONFLICT';
const CLIENT_TYPE_NOT_SUPPORTED = 'ERR_CLIENT_TYPE_NOT_SUPPORTED';
const EVENT_HANDLER_NOT_FOUND = 'ERR_EVENT_HANDLER_NOT_FOUND';
const REQUEST_TIMED_OUT = 'ERR_REQUEST_TIMED_OUT';
const PROCESSING_FAILED = 'ERR_PROCESSING_FAILED';
const PASSWORD_REQUIRED = 'ERR_PASSWORD_REQUIRED';

module.exports = {
  INTERNAL_FAILURE,
  BAD_REQUEST,
  UNAUTHORISED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  PROCESSING_FAILED,
  CLIENT_TYPE_NOT_SUPPORTED,
  EVENT_HANDLER_NOT_FOUND,
  REQUEST_TIMED_OUT,
  PASSWORD_REQUIRED
};

